# Etapa 1: Build da aplicação React
FROM node:22-alpine as build

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências
COPY package.json package-lock.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código fonte
COPY . .

# Executa o build da aplicação (assegure-se de que o script "build" está configurado no package.json)
RUN npm run build

# Etapa 2: Servir os arquivos estáticos usando o Nginx
FROM nginx:stable-alpine

# Remove a configuração padrão do Nginx (opcional, se desejar customizar)
RUN rm /etc/nginx/conf.d/default.conf

# Copia os arquivos do build para o diretório padrão do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

# Inicia o Nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]